#! /usr/bin/ruby

=begin
--------------------------------------------------------------------------------

If the source is from Git repositories, update to the latest.

Otherwise, complain.

--------------------------------------------------------------------------------
=end

$: << File.dirname(File.expand_path(__FILE__))
require 'common'

def do_update
  distro = Distro.new($settings.distro_path)

  if distro.is_release()
    raise UserInputError.new("Not a git repository: release #{distro.release_info}")
  end
  
    Dir.chdir(distro.vitro_path) { system "git pull" }
    Dir.chdir(distro.vivo_path) { system "git pull" }
end

begin
  do_update
rescue SettingsError
  puts
  puts $!
  puts
rescue UserInputError
  puts
  puts $!
  puts
end