#! /usr/bin/ruby

=begin
--------------------------------------------------------------------------------

If the source is from Git repositories, update to the latest.

Otherwise, complain.

--------------------------------------------------------------------------------
=end

$: << File.dirname(File.expand_path(__FILE__))
require 'common'

def do_update
  raise SettingsError.new("VIVO source directory is not defined") unless $settings.vivo_source
  raise SettingsError.new("Vitro source directory is not defined") unless $settings.vitro_source

  if is_git($settings.vitro_source)
    Dir.chdir($settings.vitro_source) { system "git pull" }
    Dir.chdir($settings.vivo_source) { system "git pull" }
  else
    revision_info = get_revision_info($settings.vivo_source)
    raise UserInputError.new("Not a git repository: release #{revision_info || "Unknown"}")
  end
end

begin
  do_update
rescue SettingsError
  puts $!
rescue UserInputError
  puts $!
end