#! /usr/bin/ruby

=begin
--------------------------------------------------------------------------------

If the source is from Git repositories, update to the latest.

Otherwise, complain.

--------------------------------------------------------------------------------
=end

$: << File.dirname(File.expand_path(__FILE__))
require 'common'

def check_tomcat()
  raise UserInputError.new("Stop Tomcat first.") if tomcats.which_port($settings.catalina_home)
end

def clean()
  puts system("rm -r #{$settings.catalina_home}/webapps/vivo*")
  puts system("rm -r #{$settings.catalina_home}/conf/Catalina/localhost/vivo*")
  puts system("rm -r #{$settings.catalina_home}/work/Catalina/localhost/vivo*")
end

def process_template_files()
  if @distro.is_before_1_5?
    TemplateProcessor.process($settings, @distro.file('deploy.properties.template'), @instance.file('deploy.properties'))
  else
    TemplateProcessor.process($settings, @distro.file('build.properties.template'), @instance.file('build.properties'))
  end
end

def run_build_script()
  if @distro.is_before_1_5?
    Dir.chdir(@distro.vivo_path) do
      system "ant clean deploy -Ddeploy.properties.file=#{@instance.file('deploy.properties')}"
    end
  else
    Dir.chdir(@distro.vivo_path) do
      system "ant clean deploy -Dbuild.properties.file=#{@instance.file('build.properties')}"
    end
  end
end

#
# ---------------------------------------------------------
# MAIN ROUTINE
# ---------------------------------------------------------
#

begin
  @tomcats = TomcatStatus.new()
  @distro = Distro.new($settings.distro_path)
  @instance = Instance.new($settings.instance_path)
  check_tomcat()
  clean()
  process_template_files()
  run_build_script()
rescue UserInputError
  puts $!
end
