#! /usr/bin/ruby

=begin
--------------------------------------------------------------------------------

Choose an instance from among the ~/Testing/instances/* directories, and
record that choice.

--------------------------------------------------------------------------------

To be eligible, a directory must include a instance-control.properties file with
a description. Display a list of ineligible directories along with the eligible
ones.

--------------------------------------------------------------------------------
=end

$: << File.dirname(File.expand_path(__FILE__))
require 'common'

# Find out what instances we have available
def locate_instances()
  instances_dir = ENV['HOME']+'/Testing/instances'

  @instances = []
  @invalid = []

  Dir.entries(instances_dir).sort().each() do |filename|
    next if filename.start_with?(".")

    path = File.expand_path(filename, instances_dir)
    props = InstanceControlProperties.new(path)

    if props.description
      info = {:filename => filename, :path => path, :description => props.description }
      @instances.push(info)
    else
      @invalid.push(filename)
    end
  end
end

def choose_instance()
  if (!@invalid.empty?)
    puts
    puts "Ignored invalid directories: "
    puts "     #{@invalid.join(', ')}"
  end

  puts
  puts "Enter instance number: "
  @instances.each_index do |index|
    puts "  #{index+1} = #{@instances[index][:filename]} -- #{@instances[index][:description]}"
  end

  input = STDIN.gets.chomp
  @choice = input.to_i
  if @choice <= 0 || @choice > @instances.length
    raise UserInputError.new("Invalid index: #{input}")
  end
end

def save_choice()
  File.open($settings_file, "w") do |file|
    file.puts("# What is the currently seleted instance?")
    file.puts("#{Keys::INSTANCE_PATH} = #{@instances[@choice-1][:path]}")
  end
  puts "instance set to '#{@instances[@choice-1][:filename]}'"
end

#
# ---------------------------------------------------------
# MAIN ROUTINE
# ---------------------------------------------------------
#

locate_instances()

begin
  choose_instance()
  save_choice()
rescue UserInputError
  puts "ERROR: #{$!}"
end
